<script setup lang="ts">
import { ref, onMounted, onBeforeUnmount, getCurrentInstance } from 'vue';
import { onShow, onHide } from '@dcloudio/uni-app';
import { Screen } from '../core/screen';
import { client } from '../runtime';
import CButton from './CButton.vue';
import CInput from './CInput.vue';
import CTextarea from './CTextarea.vue';
import CSwitch from './CSwitch.vue';
import CTag from './CTag.vue';
import CIcon from './CIcon.vue';
const props=defineProps<{route:string;query:Record<string,string>}>();
const vm=ref<any>(null);
const instance=getCurrentInstance();
const screen=new Screen(client,'wot',value=>{vm.value=value});
onMounted(()=>void screen.start(props.route,props.query));
onBeforeUnmount(()=>screen.dispose());onShow(()=>screen.show());onHide(()=>screen.hide());
function onAction(e:any){void screen.action(e.action||e.detail?.action||e.currentTarget?.dataset.a,String(e.arg??e.detail?.arg??e.currentTarget?.dataset.v??''))}
function onInput(e:any){const d=e.detail||e;screen.input(d.name,d.value)}
function onSearchBlur(){screen.blurSearch()}
function onFieldFocus(e:any){screen.focusField((e.detail||e).name)}
function onFieldBlur(e:any){screen.blurField((e.detail||e).name)}
function box(id:string,fn:(b:any)=>void){uni.createSelectorQuery().in(instance?.proxy).select(id).boundingClientRect(fn).exec()}
function onSliderStart(e:any){const x=e.touches[0].clientX;box('#slider-track',b=>{if(b)screen.beginSlider(x,b.width)})}
function onSliderMove(e:any){screen.moveSlider(e.touches[0].clientX)}
function onSliderEnd(){void screen.endSlider()}
function onSliderCancel(){screen.resetSlider();screen.emit()}
function onPoint(e:any){box('#point-captcha',b=>{if(b)void screen.point(e.detail.x-b.left,e.detail.y-b.top,b.width,b.height)})}
</script>
<template>
<view :class="`mini-app theme-${vm.variant} accent-${vm.preferences.accent} ${vm.preferences.reducedTransparency ? 'opaque' : ''} ${vm.dark ? 'dark' : ''}`" v-if="vm">
  <view class="topbar" :style="`padding-top:${vm.native ? vm.topInset + 6 : 6}px;padding-right:${vm.native ? 104 : 12}px`"><view class="brand" v-if="vm.view !== 'list' && vm.view !== 'messages'"><image class="logo" :src="vm.dark ? '/static/go-cinch-white.svg' : '/static/go-cinch.svg'" /><text class="brand-title">{{vm.native ? 'Go Cinch' : 'Go Cinch Admin'}}</text></view><button v-else class="icon-button" data-a="back" @tap="onAction" :aria-label="vm.l.back"><c-icon name="back" /></button><text v-if="vm.view === 'list' || vm.view === 'messages'" class="top-title">{{vm.l.manage}}</text><button v-if="vm.view !== 'auth'" class="icon-button" data-a="navigate" data-v="/msg/inbox" @tap="onAction" :aria-label="vm.l.messages"><c-icon name="bell" /><text v-if="vm.unread" class="badge">{{vm.unread}}</text></button></view>
  <scroll-view class="main-scroll" scroll-y enhanced :show-scrollbar="false">
    <view class="page">
      <view v-if="vm.booting" class="boot"><view class="skeleton sk-line"></view><view class="skeleton sk-block"></view><text>{{vm.l.loading}}</text></view>
      <block v-else>
      <view class="page-heading"><text v-if="vm.view === 'home'" class="date">{{vm.today}}</text><text class="page-title">{{vm.title}}</text><text class="lead">{{vm.subtitle}}</text></view>
      <view v-if="vm.error" class="error-box"><text>{{vm.error}}</text><c-button class="ui-button" @press="onAction" action="refresh" kind="text">{{vm.l.retry}}</c-button></view>
      <view v-if="vm.view === 'auth'" class="auth-form">
        <view v-if="vm.resetRequired" class="notice">{{vm.l.requiredReset}}</view>
        <view v-for="(item, index) in vm.authFields" :key="item.key" :class="`field ${item.error ? 'invalid' : ''}`">
          <view class="field-label-row"><text class="field-label">{{item.label}} <text v-if="item.required" class="required">*</text></text><text v-if="item.key === 'auth.username' && vm.usernameBusy" class="field-progress">{{vm.l.loading}}</text></view>
          <c-input :label="item.label" :name="item.key" :value="item.value" :password="item.kind === 'password'" :placeholder="item.placeholder" :disabled="vm.busy" @change="onInput" @focus="onFieldFocus" @blur="onFieldBlur" />
          <view v-if="item.key === 'auth.username' && vm.accountFocused && vm.accountHistory.length" class="account-history">
            <view class="account-heading"><text>{{vm.l.history}}</text><button class="account-clear" data-a="accounts-clear" @tap="onAction">{{vm.l.clearAccounts}}</button></view>
            <view v-for="(account, index) in vm.accountOptions" :key="account.value" class="account-row"><button class="account-pick" data-a="account-pick" :data-v="account.value" @tap="onAction">{{account.value}}</button><button class="icon-button" data-a="account-remove" :data-v="account.value" @tap="onAction" :aria-label="`${vm.l.remove} ${account.value}`"><c-icon name="close" /></button></view>
            <text v-if="!vm.accountOptions.length" class="account-empty">{{vm.l.noMatchingAccounts}}</text>
          </view><text v-if="item.error" class="field-error">{{item.error}}</text>
        </view>
        <view v-if="!vm.resetRequired && !vm.captcha" class="verification"><text class="field-label">{{vm.l.verification}}</text><view class="slider-track" id="slider-track"><text>{{vm.sliderBusy ? vm.l.loading : vm.proof ? vm.l.passed : vm.l.slider}}</text><view class="slider-handle" :style="`transform:translateX(${vm.sliderPosition}px)`" @touchstart="onSliderStart" @touchmove.stop.prevent="onSliderMove" @touchend="onSliderEnd" @touchcancel="onSliderCancel"><c-icon :name="vm.proof ? 'check' : 'chevron'" /></view></view></view>
        <view v-if="vm.captcha" class="verification"><view class="section-head"><text>{{vm.captcha.hint_text}}</text><c-button class="ui-button" @press="onAction" action="refresh-captcha" kind="text" :disabled="vm.sliderBusy">{{vm.l.refresh}}</c-button></view><view class="captcha" id="point-captcha" @tap="onPoint"><image :src="vm.captcha.captcha_image" mode="widthFix" /><text v-for="(item, index) in vm.captcha.points" :key="item.label" class="captcha-point" :style="`left:${item.left}%;top:${item.top}%`">{{item.label}}</text></view><text v-if="vm.captchaVerified" class="success">{{vm.l.passed}}</text></view>
        <text v-if="vm.sliderError || vm.verificationError" class="field-error">{{vm.sliderError || vm.verificationError}}</text><view class="auth-submit"><c-button class="ui-button" @press="onAction" kind="primary" action="login" :loading="vm.busy">{{vm.resetRequired ? vm.l.continue : vm.register ? vm.l.register : vm.l.login}}</c-button></view><c-button class="ui-button" @press="onAction" kind="text" action="navigate" :arg="vm.register || vm.resetRequired ? '/auth/login' : '/auth/register'">{{vm.register || vm.resetRequired ? vm.l.backToLoginLink : vm.l.createAccountLink}}</c-button>
        <view class="auth-settings-entry"><button class="settings-entry" data-a="settings" @tap="onAction"><c-icon name="settings" /><text>{{vm.l.interfaceSettings}}</text><c-icon name="chevron" /></button></view>
      </view>
      <block v-if="vm.view === 'home'">
        <view v-if="vm.canUsers" class="overview-panel"><view v-if="vm.variant !== 'ant'" class="overview-heading"><text>{{vm.l.userOverview}}</text><text class="total-number">{{vm.total}}</text></view><view class="metrics"><button v-for="(item, index) in vm.stats" :key="item.status" class="metric" data-a="home-status" :data-v="item.status" @tap="onAction"><text :class="`metric-value ${item.loading ? 'skeleton' : ''}`">{{item.loading ? ' ' : item.error ? '—' : item.value}}</text><text>{{item.label}}</text><text v-if="item.error" class="metric-error">!</text></button></view></view>
        <view v-if="vm.canUsers" class="section-head"><text class="section-title">{{vm.l.review}}</text><c-button class="ui-button" @press="onAction" kind="text" action="home-status" arg="0">{{vm.l.all}}</c-button></view>
        <view v-if="vm.canUsers" class="card"><view v-if="vm.reviewsLoading" class="skeleton sk-block"></view><button v-for="(item, index) in vm.reviews" :key="item.id" class="record" data-a="home-record" :data-v="item.name" @tap="onAction"><text class="avatar">{{item.initials}}</text><view class="record-main"><text class="record-name">{{item.name}}</text><text class="record-note">{{item.role}}</text></view><text class="review-label">{{vm.l.reviewAction}}</text></button><text v-if="!vm.reviewsLoading && !vm.reviews.length" class="empty-inline">{{vm.l.noData}}</text></view>
        <view class="section-head"><text class="section-title">{{vm.l.common}}</text><c-button class="ui-button" @press="onAction" action="navigate" arg="/dashboard/overview?tab=manage" kind="text">{{vm.l.all}}</c-button></view><view class="quick-grid"><button v-for="(item, index) in vm.quick" :key="item.resource" class="quick-item" data-a="navigate" :data-v="item.path" @tap="onAction"><view class="quick-icon"><c-icon :name="item.icon" /></view><text>{{item.label}}</text></button></view>
        <button class="security-hint" data-a="navigate" data-v="/dashboard/overview?tab=security" @tap="onAction"><c-icon name="shield" /><text>{{vm.l.security}}</text><c-icon name="chevron" /></button>
        <view v-if="vm.canUsers" class="section-head"><text class="section-title">{{vm.l.latest}}</text><c-button class="ui-button" @press="onAction" action="navigate" arg="/system/user" kind="text">{{vm.l.all}}</c-button></view><view v-if="vm.canUsers" class="card"><view v-if="vm.recentLoading" class="skeleton sk-block"></view><text v-if="vm.recentError" class="field-error">{{vm.recentError}}</text><button v-for="(item, index) in vm.recent" :key="item.id" class="record" data-a="home-record" :data-v="item.name" @tap="onAction"><text class="avatar">{{item.initials}}</text><view class="record-main"><text class="record-name">{{item.name}}</text><text class="record-note">{{item.date}}</text></view><c-icon name="chevron" /></button></view>
      </block>
      <block v-if="vm.view === 'manage'">
        <view class="search-field"><c-icon name="search" /><c-input name="search" :value="vm.query" :placeholder="vm.l.search" @change="onInput" /></view><block v-for="(group, index) in vm.groups" :key="group.title"><view class="section-head"><text class="section-title">{{group.title}}</text></view><view class="app-grid"><button v-for="(item, index) in group.items" :key="item.resource" class="app-item" data-a="navigate" :data-v="item.path" @tap="onAction"><view class="quick-icon"><c-icon :name="item.icon" /></view><text class="record-name">{{item.label}}</text><text class="record-note">{{vm.l.detail}}</text></button></view></block><view v-if="!vm.groups.length" class="empty-inline">{{vm.l.noData}}</view>
      </block>
      <block v-if="vm.view === 'list'">
        <view class="search-field"><c-icon name="search" /><c-input name="search" :value="vm.query" :placeholder="vm.l.search" @change="onInput" @blur="onSearchBlur" /></view>
        <view v-if="vm.searchFocus && vm.suggestions.length" class="card suggestions"><view class="section-head"><text>{{vm.l.suggestions}}</text><c-button class="ui-button" @press="onAction" action="clear-history" kind="text">{{vm.l.clearHistory}}</c-button></view><button v-for="(item, index) in vm.suggestions" :key="item.value" class="suggestion" data-a="suggestion" :data-v="item.value" @tap="onAction"><text v-for="(part, index) in item.parts" :key="index" :class="part.match ? 'match' : ''">{{part.value}}</text></button></view>
        <view v-if="vm.resource === 'user'" class="chips"><button v-for="(item, index) in vm.statusOptions" :key="item.value" :class="`chip ${item.active ? 'active' : ''}`" data-a="status" :data-v="item.value" @tap="onAction">{{item.label}}</button></view><view class="filter-actions"><c-button class="ui-button" @press="onAction" kind="text" action="filters">{{vm.l.filter}}</c-button><view><c-button class="ui-button" @press="onAction" kind="text" action="reset-search">{{vm.l.reset}}</c-button><c-button class="ui-button" @press="onAction" kind="text" action="search">{{vm.l.search}}</c-button></view></view>
        <view class="toolbar"><c-button class="ui-button" @press="onAction" v-if="vm.canCreate" kind="primary" action="create">＋ {{vm.l.create}}</c-button><view v-else></view><view class="toolbar-tools"><button class="icon-button" data-a="refresh" @tap="onAction" :aria-label="vm.l.refresh"><c-icon name="refresh" /></button><button class="icon-button" data-a="density" @tap="onAction" :aria-label="vm.l.density"><c-icon name="density" /></button><button class="icon-button" data-a="columns" @tap="onAction" :aria-label="vm.l.fields"><c-icon name="columns" /></button><button class="icon-button" data-a="style" @tap="onAction" :aria-label="vm.l.style"><c-icon name="grid" /></button></view></view>
        <view class="list-meta"><text>{{vm.totalLabel}}</text><c-button class="ui-button" @press="onAction" v-if="vm.canDelete" kind="text" action="select">{{vm.selection ? vm.l.done : vm.l.select}}</c-button></view><view v-if="vm.selection" class="selection-bar"><c-button class="ui-button" @press="onAction" kind="text" action="select-all">{{vm.l.allSelect}}</c-button><text>{{vm.selectedLabel}}</text><c-button class="ui-button" @press="onAction" v-if="vm.selectedCount" kind="danger" action="delete">{{vm.l.remove}}</c-button></view>
        <view v-if="vm.loading" class="card"><view class="skeleton sk-block"></view><view class="skeleton sk-block"></view><view class="skeleton sk-block"></view></view><view v-else-if="!vm.error && vm.canRead" :class="`record-list ${vm.listStyle} ${vm.density}`"><button v-for="(item, index) in vm.rows" :key="item.id" class="record" data-a="detail" :data-v="item.id" @tap="onAction"><text v-if="vm.selection" :class="`select-box ${item.selected ? 'checked' : ''}`">{{item.selected ? '✓' : ''}}</text><text v-else class="avatar">{{item.initials}}</text><view class="record-main"><text class="record-name">{{item.name}}</text><text v-for="(field, index) in item.summary" :key="field.key" class="record-note">{{field.value}}</text></view><c-tag v-if="vm.resource === 'user'" :tone="item.status === 1 ? 'success' : item.status === 2 ? 'danger' : 'warning'">{{item.statusLabel}}</c-tag><c-tag v-if="vm.resource === 'dictionary'" :tone="item.enabled ? 'success' : 'default'">{{item.enabledLabel}}</c-tag><c-icon name="chevron" /></button><view v-if="!vm.rows.length" class="empty"><c-icon name="book" /><text>{{vm.l.noData}}</text><text class="hint">{{vm.l.emptyHint}}</text></view></view>
      </block>
      <block v-if="vm.view === 'messages'"><view class="filter-actions"><view class="chips"><button :class="`chip ${vm.messageRead === 'all' ? 'active' : ''}`" data-a="message-filter" data-v="all" @tap="onAction">{{vm.l.all}}</button><button v-if="!vm.isSent" :class="`chip ${vm.messageRead === 'unread' ? 'active' : ''}`" data-a="message-filter" data-v="unread" @tap="onAction">{{vm.l.unread}}</button></view><c-button class="ui-button" @press="onAction" v-if="!vm.isSent" action="read-all" kind="text">{{vm.l.allRead}}</c-button><c-button class="ui-button" @press="onAction" v-if="vm.isSent && vm.canSend" action="compose" kind="primary">{{vm.l.send}}</c-button></view><view v-if="vm.loading" class="skeleton sk-block"></view><view v-else class="card"><button v-for="(item, index) in vm.messageRows" :key="item.id" class="message-row" data-a="detail" :data-v="item.id" @tap="onAction"><view class="message-title"><text v-if="!item.read" class="unread-dot"></text><text>{{item.title}}</text></view><text class="message-preview">{{item.content}}</text><view class="message-meta"><text>{{item.date}}</text><c-tag>{{item.type}}</c-tag></view></button><view v-if="!vm.error && !vm.messageRows.length" class="empty">{{vm.l.noData}}</view></view></block>
      <view v-if="vm.view === 'list' || vm.view === 'messages'" class="pagination"><c-button class="ui-button" @press="onAction" kind="text" action="prev" :disabled="vm.page <= 1 || vm.loading">{{vm.l.prev}}</c-button><text>{{vm.pageLabel}}</text><c-button class="ui-button" @press="onAction" kind="text" action="page-size">{{vm.size}}</c-button><c-button class="ui-button" @press="onAction" kind="text" action="next" :disabled="vm.page >= vm.pages || vm.loading">{{vm.l.next}}</c-button></view>
      <block v-if="vm.view === 'profile' || vm.view === 'security'"><view class="profile-card"><text class="avatar large">{{vm.initials}}</text><view><text class="record-name">{{vm.user.username}}</text><text class="record-note">{{vm.user.role.name || vm.l.session}}</text><text class="record-note">{{vm.user.code}}</text></view></view><view class="section-head"><text class="section-title">{{vm.l.session}}</text></view><view class="card"><button class="menu-row" data-a="profile" @tap="onAction"><c-icon name="user" /><text>{{vm.l.profile}}</text><c-icon name="chevron" /></button><button class="menu-row" data-a="password" @tap="onAction"><c-icon name="key" /><text>{{vm.l.passwordChange}}</text><c-icon name="chevron" /></button><button v-if="vm.view === 'security'" class="menu-row" data-a="lock" @tap="onAction"><c-icon name="shield" /><text>{{vm.l.lock}}</text><c-icon name="chevron" /></button></view><view class="section-head"><text class="section-title">{{vm.l.settings}}</text></view><view class="card"><button class="menu-row" data-a="settings" @tap="onAction"><c-icon name="settings" /><text class="menu-label">{{vm.l.interfaceSettings}}</text><c-icon name="chevron" /></button></view><view class="logout"><c-button class="ui-button" @press="onAction" action="logout" kind="danger">{{vm.l.logout}}</c-button></view></block>
      </block>
      <view v-if="vm.footer" class="copyright"><text>{{vm.copyright}}</text><text v-if="vm.icp">{{vm.icp}}</text></view>
    </view>
  </scroll-view>
  <view v-if="vm.view !== 'auth'" class="dock"><button v-for="(item, index) in vm.dock" :key="item.key" :class="`dock-item ${item.active ? 'active' : ''}`" data-a="navigate" :data-v="item.path" @tap="onAction"><c-icon :name="item.icon" /><text>{{item.label}}</text></button></view>
  <view v-if="vm.settingsOpen" class="settings-screen">
    <view class="settings-topbar" :style="`padding-top:${vm.native ? vm.topInset + 6 : 6}px;padding-right:${vm.native ? 104 : 16}px`"><button class="icon-button" data-a="close" @tap="onAction" :aria-label="vm.l.back"><c-icon name="back" /></button><text class="settings-title">{{vm.l.interfaceSettings}}</text></view>
    <scroll-view class="settings-scroll" scroll-y enhanced :show-scrollbar="false"><view class="settings-body">
      <text class="settings-description">{{vm.l.settingsDescription}}</text>
      <text class="settings-section-label">{{vm.l.appearance}}</text>
      <view class="settings-group">
        <view class="settings-row"><view class="settings-icon"><view class="settings-moon"></view></view><view class="settings-copy"><text class="settings-row-title">{{vm.l.dark}}</text></view><c-switch class="ui-switch" name="preference.dark" :checked="vm.preferences.dark" @change="onInput" /></view>
        <view class="settings-row"><view class="settings-icon"><c-icon name="layers" /></view><view class="settings-copy"><text class="settings-row-title">{{vm.l.reduced}}</text><text class="settings-row-note">{{vm.l.reducedHint}}</text></view><c-switch class="ui-switch" name="preference.reducedTransparency" :checked="vm.preferences.reducedTransparency" @change="onInput" /></view>
        <view class="settings-color-section"><text class="settings-row-title">{{vm.l.color}}</text><view class="palette-options"><button v-for="(item, index) in vm.palette" :key="item.value" :class="`palette-option ${item.selected ? 'selected' : ''}`" data-a="accent" :data-v="item.value" @tap="onAction" :aria-pressed="item.selected"><view class="palette-color" :style="`background-color:${item.color}`"><text v-if="item.selected">✓</text></view><text>{{item.label}}</text></button></view></view>
      </view>
      <text class="settings-section-label">{{vm.l.general}}</text>
      <view class="settings-group">
        <button class="settings-row" data-a="language" @tap="onAction"><view class="settings-icon"><c-icon name="globe" /></view><view class="settings-copy"><text class="settings-row-title">{{vm.l.language}}</text></view><text class="settings-value">{{vm.language}}</text><c-icon name="chevron" /></button>
        <button class="settings-row" data-a="timezone" @tap="onAction"><view class="settings-icon"><c-icon name="clock" /></view><view class="settings-copy"><text class="settings-row-title">{{vm.l.timezone}}</text></view><text class="settings-value">{{vm.preferences.timezone}}</text><c-icon name="chevron" /></button>
      </view>
      <text class="settings-section-label">{{vm.l.layout}}</text>
      <view class="settings-group">
        <view class="settings-row"><view class="settings-icon"><c-icon name="layout" /></view><view class="settings-copy"><text class="settings-row-title">{{vm.l.footer}}</text></view><c-switch class="ui-switch" name="preference.footer" :checked="vm.preferences.footer" @change="onInput" /></view>
        <button class="settings-row" data-a="preferences" @tap="onAction"><view class="settings-icon"><c-icon name="book" /></view><view class="settings-copy"><text class="settings-row-title">{{vm.l.copyrightInfo}}</text></view><text class="settings-value">{{vm.preferences.company}}</text><c-icon name="chevron" /></button>
      </view><text class="settings-footnote">{{vm.l.settingsSaved}}</text>
    </view></scroll-view>
  </view>
  <view v-if="vm.sheet && vm.sheet.type !== 'settings'" class="overlay"><view class="mask" data-a="close" @tap="onAction"></view><view class="sheet"><view class="handle"></view><view class="sheet-header"><text>{{vm.sheet.title}}</text><button class="icon-button" data-a="close" @tap="onAction" :aria-label="vm.l.close"><c-icon name="close" /></button></view><scroll-view scroll-y class="sheet-scroll"><view class="sheet-body">
    <text v-if="vm.sheetError" class="field-error">{{vm.sheetError}}</text><view v-if="vm.sheet.loading" class="skeleton sk-block"></view>
    <block v-if="vm.sheet.type === 'detail' || vm.sheet.type === 'profile'"><text class="detail-name">{{vm.recordName}}</text><view v-for="(item, index) in vm.details" :key="item.key" class="detail-field"><text class="detail-label">{{item.label}}</text><scroll-view v-if="item.json" class="json-box" scroll-y><text selectable>{{item.value}}</text></scroll-view><view v-else class="detail-value"><text v-for="(tag, index) in item.tags" :key="index">{{tag}}</text></view></view></block>
    <view v-for="(item, index) in vm.fields" :key="item.key" :class="`field ${item.error ? 'invalid' : ''}`"><text class="field-label">{{item.label}} <text v-if="item.required" class="required">*</text></text><c-switch class="ui-switch" v-if="item.kind === 'switch'" :name="item.key" :checked="item.value" @change="onInput" /><c-button class="ui-button" @press="onAction" v-else-if="item.kind === 'picker'" kind="outline" action="picker" :arg="item.key">{{item.display}}</c-button><c-textarea v-else-if="item.kind === 'textarea'" :name="item.key" :value="item.value" :placeholder="item.placeholder" :disabled="vm.busy" @change="onInput" /><c-input v-else :name="item.key" :value="item.value" :password="item.kind === 'password'" :placeholder="item.placeholder" :disabled="vm.busy" @change="onInput" /><text v-if="item.key === 'form.year'" class="hint">{{vm.l.autoYearHint}}</text><text v-if="item.error" class="field-error">{{item.error}}</text></view>
    <block v-if="vm.sheet.type === 'password' && vm.captcha"><view class="section-head"><text>{{vm.captcha.hint_text}}</text><c-button class="ui-button" @press="onAction" action="refresh-captcha" kind="text">{{vm.l.refresh}}</c-button></view><view class="captcha" id="point-captcha" @tap="onPoint"><image :src="vm.captcha.captcha_image" mode="widthFix" /><text v-for="(item, index) in vm.captcha.points" :key="item.label" class="captcha-point" :style="`left:${item.left}%;top:${item.top}%`">{{item.label}}</text></view><text v-if="vm.verificationError || vm.sliderError" class="field-error">{{vm.verificationError || vm.sliderError}}</text></block>
    <view v-if="vm.sheet.type === 'picker'" class="search-field"><c-icon name="search" /><c-input name="picker" :value="vm.optionsQuery" :placeholder="vm.l.search" @change="onInput" /></view><view v-if="vm.optionsLoading" class="skeleton sk-block"></view><button v-for="(item, index) in vm.choices" :key="item.value" :class="`option ${item.selected ? 'active' : ''}`" :data-a="item.action" :data-v="item.value" @tap="onAction"><text>{{item.label}}</text><text>{{item.selected ? '✓' : ''}}</text></button><c-button class="ui-button" @press="onAction" v-if="vm.sheet.type === 'picker' && vm.optionsMore" action="options-more" kind="text">{{vm.l.loadMore}}</c-button><c-button class="ui-button" @press="onAction" v-if="vm.sheet.type === 'picker' && vm.sheetError" action="options-retry" kind="text">{{vm.l.retry}}</c-button>
    <block v-if="vm.sheet.type === 'preferences'"><text class="settings-hint">{{vm.l.copyrightHiddenHint}}</text><view class="remember-row"><text>{{vm.l.copyrightVisible}}</text><c-switch class="ui-switch" name="form.copyright" :checked="vm.form.copyright" @change="onInput" /></view></block>
    <block v-if="vm.sheet.type === 'operation' && vm.sheet.operation === 'review'"><view class="chips"><button :class="`chip ${vm.form.decision === 'approve' ? 'active' : ''}`" data-a="decision" data-v="approve" @tap="onAction">{{vm.extra.approve}}</button><button :class="`chip ${vm.form.decision === 'reject' ? 'active' : ''}`" data-a="decision" data-v="reject" @tap="onAction">{{vm.extra.reject}}</button></view></block><block v-if="vm.sheet.type === 'operation' && vm.sheet.operation === 'lock'"><view class="chips"><button :class="`chip ${vm.form.lockMode === 'until' ? 'active' : ''}`" data-a="lock-mode" data-v="until" @tap="onAction">{{vm.extra.until}}</button><button :class="`chip ${vm.form.lockMode === 'permanent' ? 'active' : ''}`" data-a="lock-mode" data-v="permanent" @tap="onAction">{{vm.extra.permanent}}</button></view></block>
    <block v-if="vm.sheet.type === 'compose'"><text class="field-label">{{vm.extra.messageType}}</text><view class="chips"><button :class="`chip ${vm.form.type === 'notice' ? 'active' : ''}`" data-a="message-type" data-v="notice" @tap="onAction">{{vm.extra.notice}}</button><button :class="`chip ${vm.form.type === 'system' ? 'active' : ''}`" data-a="message-type" data-v="system" @tap="onAction">{{vm.extra.system}}</button></view><text class="field-label">{{vm.extra.scope}}</text><view class="chips"><button :class="`chip ${vm.form.scope === 'all' ? 'active' : ''}`" data-a="message-scope" data-v="all" @tap="onAction">{{vm.l.all}}</button><button :class="`chip ${vm.form.scope === 'targeted' ? 'active' : ''}`" data-a="message-scope" data-v="targeted" @tap="onAction">{{vm.extra.targeted}}</button></view></block>
    <view v-if="vm.sheet.type === 'message'" class="message-detail"><text class="detail-name">{{vm.message.title}}</text><text class="record-note">{{vm.message.date}} · {{vm.message.type}}</text><text class="message-content" selectable>{{vm.message.content}}</text></view>
    <text v-if="vm.sheet.type === 'discard'" class="lead">{{vm.extra.discardHint}}</text>
  </view></scroll-view><view class="sheet-footer">
    <block v-if="vm.sheet.type === 'detail' && !vm.sheet.loading && !vm.sheetError"><c-button class="ui-button" @press="onAction" v-if="vm.canDelete" kind="danger" action="delete">{{vm.l.remove}}</c-button><c-button class="ui-button" @press="onAction" v-if="vm.canUpdate" kind="primary" action="edit">{{vm.l.edit}}</c-button><c-button class="ui-button" @press="onAction" v-if="vm.resource === 'user' && vm.canUpdate && vm.recordStatus === 0" action="review">{{vm.l.reviewAction}}</c-button><c-button class="ui-button" @press="onAction" v-if="vm.resource === 'user' && vm.canUpdate" :action="vm.recordStatus === 2 ? 'unlock-user' : 'lock-user'">{{vm.recordStatus === 2 ? vm.extra.unlock : vm.extra.lock}}</c-button><c-button class="ui-button" @press="onAction" v-if="vm.resource === 'user' && vm.canUpdate && vm.hasPasswordLock" action="unlock-password">{{vm.extra.unlockPassword}}</c-button></block>
    <c-button class="ui-button" @press="onAction" v-if="vm.sheet.type === 'edit'" kind="primary" action="save" :loading="vm.busy">{{vm.l.save}}</c-button><c-button class="ui-button" @press="onAction" v-if="vm.sheet.type === 'password'" kind="primary" action="save-password" :loading="vm.busy">{{vm.l.save}}</c-button><c-button class="ui-button" @press="onAction" v-if="vm.sheet.type === 'compose'" kind="primary" action="send" :loading="vm.busy">{{vm.l.send}}</c-button><c-button class="ui-button" @press="onAction" v-if="vm.sheet.type === 'timezone'" kind="primary" action="timezone-save">{{vm.l.save}}</c-button><c-button class="ui-button" @press="onAction" v-if="vm.sheet.type === 'preferences'" kind="primary" action="save-preferences">{{vm.l.save}}</c-button><c-button class="ui-button" @press="onAction" v-if="vm.sheet.type === 'filters'" kind="primary" action="apply-filters">{{vm.l.confirm}}</c-button><c-button class="ui-button" @press="onAction" v-if="vm.sheet.type === 'picker' || vm.sheet.type === 'columns' || vm.sheet.type === 'language'" kind="primary" action="close">{{vm.l.done}}</c-button>
    <block v-if="vm.sheet.type === 'operation'"><c-button class="ui-button" @press="onAction" action="close">{{vm.l.cancel}}</c-button><c-button class="ui-button" @press="onAction" kind="primary" action="operate" :loading="vm.busy">{{vm.l.confirm}}</c-button></block><block v-if="vm.sheet.type === 'discard'"><c-button class="ui-button" @press="onAction" action="keep-editing">{{vm.extra.keep}}</c-button><c-button class="ui-button" @press="onAction" kind="danger" action="discard">{{vm.extra.discard}}</c-button></block><block v-if="vm.sheet.type === 'logout'"><c-button class="ui-button" @press="onAction" action="close">{{vm.l.cancel}}</c-button><c-button class="ui-button" @press="onAction" kind="danger" action="confirm-logout" :loading="vm.busy">{{vm.l.logout}}</c-button></block><c-button class="ui-button" @press="onAction" v-if="vm.sheet.type === 'message' && vm.canDeleteMessage" kind="danger" action="delete">{{vm.l.remove}}</c-button>
  </view></view></view>
</view>

</template>
